export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  USER_EXISTS: 'USER_EXISTS',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_NAME_DUPLICATE: 'TAG_NAME_DUPLICATE',
  INVALID_TAG: 'INVALID_TAG',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
